import { clone, create, fromBinary, toBinary, toJson } from "@bufbuild/protobuf";
import { AppOnly, Channel, ClientOnly, LocalOnly, Mesh, ModuleConfig } from "@meshtastic/protobufs";
import { effectiveDefaults, sectionMap, sections } from "./config";
import type { ChannelDraft, ChannelImport, Draft, ExportWarning, FieldValue, InstanceConfig, InstancePreset, LocationDraft, SectionDraft, SectionId } from "./types";
import { byteLength } from "../vendor/nodenavngenerator/src/nameGenerator";

export const DEFAULT_CHANNEL_KEY = "AQ==";
export function bytesToBase64(bytes: Uint8Array): string { let binary = ""; for (const byte of bytes) binary += String.fromCharCode(byte); return btoa(binary); }
export function base64ToBytes(value: string): Uint8Array { const normalized = value.replace(/-/g, "+").replace(/_/g, "/").replace(/\s/g, ""); const padded = normalized + "=".repeat((4 - normalized.length % 4) % 4); return Uint8Array.from(atob(padded), (c) => c.charCodeAt(0)); }
export function base64Url(bytes: Uint8Array): string { return bytesToBase64(bytes).replace(/=/g, "").replace(/\+/g, "-").replace(/\//g, "_"); }
function normalize(value: unknown): FieldValue { if (value instanceof Uint8Array) return bytesToBase64(value); if (Array.isArray(value)) return value.map((v) => v instanceof Uint8Array ? bytesToBase64(v) : v) as number[]; if (["bigint", "boolean", "number", "string"].includes(typeof value)) return value as FieldValue; return ""; }
function denormalize(value: FieldValue, scalar?: number, list = false): unknown { if (scalar === 12) return list ? (Array.isArray(value) ? value.map((v) => base64ToBytes(String(v))) : []) : base64ToBytes(String(value)); if (scalar === 4 || scalar === 6 || scalar === 18) return BigInt(String(value || 0)); return value; }
export function roleCodeForValue(value: number): string { return ({ 0: "C", 1: "M", 2: "R", 5: "T", 6: "S", 8: "H", 9: "F", 10: "E", 11: "L", 12: "B" } as Record<number, string>)[value] ?? ""; }
export function emptyLocation(): LocationDraft { return { latitude: "", longitude: "", altitude: "", municipalityNumber: "", municipalityCode: "", municipalityName: "", countyName: "", placeName: "", placeNameEdited: false, municipalityOverride: false }; }
export function createSection(instance: InstanceConfig, preset: InstancePreset, format: Draft["profileFormat"], id: SectionId, included = false): SectionDraft { return { included, imported: false, values: effectiveDefaults(instance, preset, format, id, preset.defaults.role) }; }
export function resetField(draft: Draft, instance: InstanceConfig, field: string, id: SectionId): Draft { const preset = instance.presets.find((p) => p.id === draft.presetId) ?? instance.presets.find((p) => p.id === instance.defaultPreset)!; const defaults = effectiveDefaults(instance, preset, draft.profileFormat, id, Number(draft.sections.device.values.role)); return { ...draft, sections: { ...draft.sections, [id]: { ...draft.sections[id], values: { ...draft.sections[id].values, [field]: defaults[field] } } } }; }

export function createDraft(instance: InstanceConfig, preset = instance.presets.find((p) => p.id === instance.defaultPreset)!): Draft {
  const draftSections = Object.fromEntries(sections.map(({ id }) => [id, createSection(instance, preset, instance.defaultFormat, id)])) as Record<SectionId, SectionDraft>;
  draftSections.lora.included = true; draftSections.device.included = true; draftSections.position.included = true;
  const mqttProvider = instance.mqttProviders.find((p) => p.recommended) ?? instance.mqttProviders[0];
  return { schemaVersion: 2, profileFormat: instance.defaultFormat, presetId: preset.id, customLongName: false, naming: { roleCode: "", municipality: "", location: "", owner: "", suffix: "" }, longName: "", shortName: "", channelsIncluded: false, channels: [newChannel(true)], sections: draftSections, location: emptyLocation(), guided: { radio: "community", roleChosen: false, gps: "", mapReporting: false, mqttConsent: false, mqttProvider: mqttProvider?.id ?? "", mqttRegionRequired: Boolean(mqttProvider?.regionalRoot), mqttTransport: "proxy", mqttRegion: "" }, preserveImported: { topLevel: true, config: true, moduleConfig: true } };
}
export function newChannel(primary = false): ChannelDraft { return { id: crypto.randomUUID(), name: "", psk: DEFAULT_CHANNEL_KEY, uplinkEnabled: false, downlinkEnabled: false, positionPrecision: 0, primary }; }
function channelSettings(channel: ChannelDraft) { return create(Channel.ChannelSettingsSchema, { name: channel.name, psk: base64ToBytes(channel.psk), uplinkEnabled: channel.uplinkEnabled, downlinkEnabled: channel.downlinkEnabled, moduleSettings: create(Channel.ModuleSettingsSchema, { positionPrecision: channel.positionPrecision }) }); }
export function channelUrlFromDraft(draft: Draft, includeLora: boolean, additive = false): string { const ordered = [...draft.channels].sort((a, b) => Number(b.primary) - Number(a.primary)); const input: Record<string, unknown> = { settings: ordered.map(channelSettings) }; if (includeLora && draft.sections.lora.included) input.loraConfig = buildSectionMessage(draft.sections.lora, "lora"); const payload = base64Url(toBinary(AppOnly.ChannelSetSchema, create(AppOnly.ChannelSetSchema, input))); return `https://meshtastic.org/e/${additive ? "?add=true" : ""}#${payload}`; }
export function parseChannelUrl(value: string): ChannelImport { const trimmed = value.trim(); const additive = /[?&]add=true(?:&|#|$)/i.test(trimmed); const payload = trimmed.includes("#") ? trimmed.split("#").pop()!.split("?")[0] : trimmed.split("?")[0]; if (!payload) throw new Error("The channel URL does not contain a payload"); const set = fromBinary(AppOnly.ChannelSetSchema, base64ToBytes(payload)) as Record<string, any>; if (!Array.isArray(set.settings) || set.settings.length < 1 || set.settings.length > 8) throw new Error("The channel set must contain between one and eight channels"); const channels = set.settings.map((s: Record<string, any>, i: number) => ({ id: crypto.randomUUID(), name: s.name ?? "", psk: bytesToBase64(s.psk ?? new Uint8Array()), uplinkEnabled: Boolean(s.uplinkEnabled), downlinkEnabled: Boolean(s.downlinkEnabled), positionPrecision: Number(s.moduleSettings?.positionPrecision ?? 0), primary: i === 0 })); return { channels, lora: set.loraConfig ? readFields("lora", set.loraConfig) : undefined, additive };
}
export function channelsEqual(a: ChannelDraft, b: ChannelDraft): boolean { return a.name === b.name && a.psk === b.psk && a.uplinkEnabled === b.uplinkEnabled && a.downlinkEnabled === b.downlinkEnabled && a.positionPrecision === b.positionPrecision; }
export function previewAdditiveChannels(current: ChannelDraft[], incoming: ChannelDraft[]) { const additions: ChannelDraft[] = []; const duplicates: ChannelDraft[] = []; const conflicts: ChannelDraft[] = []; for (const channel of incoming) { const same = current.find((c) => c.name === channel.name); if (same && channelsEqual(same, channel)) duplicates.push(channel); else if (same) conflicts.push(channel); else additions.push({ ...channel, primary: false }); } return { additions, duplicates, conflicts, capacity: Math.max(0, 8 - current.length) }; }
export function applyChannelImport(current: ChannelDraft[], incoming: ChannelDraft[], additive: boolean): ChannelDraft[] { if (!additive) return incoming.slice(0, 8).map((c, i) => ({ ...c, primary: i === 0 })); const preview = previewAdditiveChannels(current, incoming); return [...current, ...preview.additions.slice(0, preview.capacity)].map((c, i) => ({ ...c, primary: i === 0 })); }

export function buildSectionMessage(section: SectionDraft, id: SectionId, imported?: unknown): Record<string, unknown> { const definition = sectionMap[id]; const message = imported ? clone(definition.schema, imported as never) as Record<string, unknown> : create(definition.schema) as Record<string, unknown>; for (const field of definition.schema.fields) if (definition.editable.includes(field.localName)) message[field.localName] = denormalize(section.values[field.localName], field.scalar, field.fieldKind === "list"); if (id === "lora") { if (message.usePreset) { message.bandwidth = 0; message.spreadFactor = 0; message.codingRate = 0; } else message.modemPreset = 0; } return message; }
function readFields(id: SectionId, message: Record<string, unknown>): Record<string, FieldValue> { return Object.fromEntries(sectionMap[id].editable.map((field) => [field, normalize(message[field])])); }
function decodedBase(draft: Draft): Record<string, any> { return draft.importedBinary ? fromBinary(ClientOnly.DeviceProfileSchema, base64ToBytes(draft.importedBinary), { readUnknownFields: true }) as Record<string, any> : create(ClientOnly.DeviceProfileSchema) as Record<string, any>; }
export function buildProfile(draft: Draft): Record<string, any> {
  const profile = decodedBase(draft); if (!draft.preserveImported.topLevel) { profile.ringtone = undefined; profile.cannedMessages = undefined; profile.$unknown = []; }
  profile.longName = draft.longName; profile.shortName = draft.shortName; profile.channelUrl = draft.channelsIncluded ? channelUrlFromDraft(draft, draft.sections.lora.included) : undefined;
  for (const target of ["config", "moduleConfig"] as const) { const defs = sections.filter((d) => d.target === target); const preserve = draft.preserveImported[target]; const schema = target === "config" ? LocalOnly.LocalConfigSchema : LocalOnly.LocalModuleConfigSchema; const existing = profile[target]; profile[target] = defs.some((d) => draft.sections[d.id].included) || (preserve && existing) ? (preserve && existing ? clone(schema, existing) : create(schema)) : undefined; }
  for (const definition of sections) { const container = profile[definition.target] as Record<string, unknown> | undefined; if (!container) continue; if (!draft.sections[definition.id].included) { container[definition.targetKey] = undefined; continue; } const existing = container[definition.targetKey]; container[definition.targetKey] = buildSectionMessage(draft.sections[definition.id], definition.id, existing); }
  if (profile.moduleConfig?.mqtt && draft.sections.mqtt.included) profile.moduleConfig.mqtt.mapReportSettings = create(ModuleConfig.ModuleConfig_MapReportSettingsSchema, { shouldReportLocation: draft.guided.mapReporting, positionPrecision: 14, publishIntervalSecs: 3600 });
  const lat = Number(draft.location.latitude), lon = Number(draft.location.longitude); if (draft.location.latitude !== "" && draft.location.longitude !== "" && Number.isFinite(lat) && Number.isFinite(lon)) profile.fixedPosition = create(Mesh.PositionSchema, { latitudeI: Math.round(lat * 1e7), longitudeI: Math.round(lon * 1e7), altitude: Math.round(Number(draft.location.altitude || 0)) }); else profile.fixedPosition = undefined;
  return profile;
}
export function encodeProfile(draft: Draft): Uint8Array { return toBinary(ClientOnly.DeviceProfileSchema, buildProfile(draft) as never, { writeUnknownFields: true }); }
export function profileJson(draft: Draft): unknown { return toJson(ClientOnly.DeviceProfileSchema, buildProfile(draft) as never, { emitDefaultValues: false, enumAsInteger: false }); }
export function importProfile(bytes: Uint8Array, fileName: string, instance: InstanceConfig): Draft { const profile = fromBinary(ClientOnly.DeviceProfileSchema, bytes, { readUnknownFields: true }) as Record<string, any>; const draft = createDraft(instance); draft.importedBinary = bytesToBase64(bytes); draft.importedFileName = fileName; draft.longName = profile.longName ?? ""; draft.shortName = profile.shortName ?? ""; draft.customLongName = true; for (const def of sections) { const message = profile[def.target]?.[def.targetKey] as Record<string, unknown> | undefined; const section = draft.sections[def.id]; section.included = Boolean(message); section.imported = Boolean(message); if (message) section.values = readFields(def.id, message); } draft.channelsIncluded = Boolean(profile.channelUrl); if (profile.channelUrl) try { draft.channels = parseChannelUrl(profile.channelUrl).channels; } catch { draft.channels = [newChannel(true)]; } if (profile.fixedPosition) { draft.location.latitude = String(Number(profile.fixedPosition.latitudeI ?? 0) / 1e7); draft.location.longitude = String(Number(profile.fixedPosition.longitudeI ?? 0) / 1e7); draft.location.altitude = String(profile.fixedPosition.altitude ?? ""); } const gps = Number(draft.sections.position.values.gpsMode); draft.guided.gps = gps === 1 ? "enabled" : gps === 2 ? "absent" : "disabled"; draft.guided.roleChosen = draft.sections.device.included; draft.naming.roleCode = roleCodeForValue(Number(draft.sections.device.values.role)); draft.guided.mapReporting = Boolean(profile.moduleConfig?.mqtt?.mapReportingEnabled); return draft; }
export function migrateDraft(value: unknown, instance: InstanceConfig): Draft { if (!value || typeof value !== "object") return createDraft(instance); const old = value as any; if (old.schemaVersion === 2) { const current = old as Draft; const provider = instance.mqttProviders.find((item) => item.id === current.guided?.mqttProvider); const profileFormat = instance.formats.some((format) => format.id === current.profileFormat) ? current.profileFormat : instance.defaultFormat; return { ...current, profileFormat, guided: { ...current.guided, mqttRegionRequired: current.guided?.mqttRegionRequired ?? Boolean(provider?.regionalRoot) } }; } const draft = createDraft(instance); const preset = instance.presets.find((p) => p.id === old.presetId) ?? instance.presets.find((p) => p.id === instance.defaultPreset)!; for (const def of sections) { const source = old.sections?.[def.id]; if (!source) continue; draft.sections[def.id].included = Boolean(source.included); draft.sections[def.id].imported = Boolean(source.imported); const defaults = effectiveDefaults(instance, preset, instance.defaultFormat, def.id); for (const field of def.editable) draft.sections[def.id].values[field] = source.selected?.[field] ? source.values?.[field] : defaults[field]; } Object.assign(draft, { importedBinary: old.importedBinary, importedFileName: old.importedFileName, longName: old.longName ?? "", shortName: old.shortName ?? "", channelsIncluded: Boolean(old.channelsIncluded), channels: old.channels?.length ? old.channels : draft.channels, customLongName: old.longNameMode === "custom", naming: old.naming ?? draft.naming, location: { ...draft.location, ...(old.location ?? {}) }, preserveImported: old.preserveImported ?? draft.preserveImported }); return draft; }
export function shortNameSuggestions(owner: string, location: string): string[] { const out: string[] = []; for (const source of [owner, location]) { const words = source.normalize("NFC").trim().split(/[\s-]+/).filter(Boolean); const initials = words.map((w) => Array.from(w)[0]).join("").toLocaleUpperCase("nb-NO"); if (initials && byteLength(initials) <= 4) out.push(initials); let leading = ""; for (const c of Array.from(source.normalize("NFC").toLocaleUpperCase("nb-NO").replace(/\s/g, ""))) { if (byteLength(leading + c) > 4) break; leading += c; } if (leading) out.push(leading); } return [...new Set(out)].slice(0, 4); }
export function validateDraft(draft: Draft): string[] { const errors: string[] = []; if (!draft.guided.roleChosen) errors.push("Choose a device role"); if (!draft.guided.gps) errors.push("Choose the node's GPS hardware state"); if (!draft.customLongName && (!draft.naming.roleCode || !draft.naming.municipality || !draft.naming.location)) errors.push("The naming convention requires role, municipality, and location"); if (!draft.longName || byteLength(draft.longName) > 24) errors.push("Long name must contain 1–24 UTF-8 bytes"); if (!draft.shortName || byteLength(draft.shortName) > 4) errors.push("Short name must contain 1–4 UTF-8 bytes"); if ((draft.guided.mapReporting || draft.guided.mqttConsent) && !draft.guided.mqttProvider) errors.push("Choose an MQTT provider"); if ((draft.guided.mapReporting || draft.guided.mqttConsent) && draft.guided.mqttRegionRequired && !draft.guided.mqttRegion) errors.push("Choose an MQTT region"); if (draft.guided.mqttTransport === "wifi" && !String(draft.sections.network.values.wifiSsid)) errors.push("Enter the Wi-Fi SSID"); if (draft.channelsIncluded && (draft.channels.length < 1 || draft.channels.length > 8)) errors.push("A channel set must contain 1–8 channels"); for (const c of draft.channels) { if (byteLength(c.name) > 11) errors.push("Channel names must be shorter than 12 UTF-8 bytes"); try { if (![0, 1, 16, 32].includes(base64ToBytes(c.psk).length)) errors.push("Channel keys must contain 0, 1, 16, or 32 bytes"); } catch { errors.push("Channel keys must be valid Base64"); } } const lat = draft.location.latitude === "" ? NaN : Number(draft.location.latitude), lon = draft.location.longitude === "" ? NaN : Number(draft.location.longitude); if ((Number.isFinite(lat) && Math.abs(lat) > 90) || (Number.isFinite(lon) && Math.abs(lon) > 180)) errors.push("Coordinates are outside valid ranges"); return errors; }
export function exportWarnings(draft: Draft): ExportWarning[] { const warnings: ExportWarning[] = []; if (Number(draft.sections.device.values.role) === 2) warnings.push({ id: "router", level: "strict", text: "Router is an infrastructure role. Use it only for a deliberately placed, continuously available node." }); if (Number(draft.sections.lora.values.hopLimit) > 3) warnings.push({ id: "hops", level: "strict", text: "Hop limits above 3 increase mesh traffic and must be used deliberately." }); if (draft.channels.some((c) => !["", DEFAULT_CHANNEL_KEY].includes(c.psk))) warnings.push({ id: "channel-key", level: "strict", text: "This artifact contains custom channel keys. Anyone who receives it can join those channels." }); const sensitive = sections.some((def) => def.sensitive?.some((field) => def.id in draft.sections && draft.sections[def.id].included && String(draft.sections[def.id].values[field] ?? "") !== "")); if (sensitive) warnings.push({ id: "secrets", level: "strict", text: "This profile contains passwords or cryptographic keys. Share it only with trusted recipients." }); if (draft.location.latitude && draft.location.longitude) warnings.push({ id: "location", level: "warning", text: "This profile contains an initial position." }); return warnings; }
export function inspectUnknownFields(draft: Draft) { if (!draft.importedBinary) return { topLevel: 0, preservedBytes: 0 }; const profile = fromBinary(ClientOnly.DeviceProfileSchema, base64ToBytes(draft.importedBinary), { readUnknownFields: true }) as any; return { topLevel: profile.$unknown?.length ?? 0, preservedBytes: base64ToBytes(draft.importedBinary).length }; }
